### ISSUE TITLE
Tkinter window breaks when attempting to draw an emoji

### ISSUE THREAD

**Issue by parklez** [parklez/twitch-bot#11]
```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Andreas\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:\Users\Andreas\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 746, in callit
    func(*args)
  File "C:\Users\Andreas\Documents\GitHub\twitch-bot\parky_bot\gui\console_widget.py", line 48, in pooling
    self.insert(message)
  File "C:\Users\Andreas\Documents\GitHub\twitch-bot\parky_bot\gui\console_widget.py", line 56, in insert
    self.console.insert(tkinter.END, f'{message}\n', text.levelname)
  File "C:\Users\Andreas\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 3269, in insert
    self.tk.call((self._w, 'insert', index, chars) + args)
_tkinter.TclError: character U+1f633 is above the range (U+0000-U+FFFF) allowed by Tcl
```
![image](https://user-images.githubusercontent.com/29131182/104370575-d6ac3080-54fd-11eb-920f-4ee2ee1b8c97.png)

**Comment by parklez** [comment]
"Fixed" with https://github.com/parklez/twitch-bot/commit/f62f67efb48e00d9c1f8ff6cbd7bdb2246f720c2
