### ISSUE TITLE
Message regex problems

### ISSUE THREAD

**Issue by parklez** [parklez/twitch-bot#24]
`@badge-info=subscriber/45;badges=broadcaster/1,subscriber/0,premium/1;client-nonce=e82f3c0e5259ab25d21f55fe8096ba00;color=#88CEFF;display-name=leparklez;emotes=1:4-5;flags=0-2:P.3;id=46a94f45-b6f8-4094-80a2-472a1f8cefe8;mod=0;room-id=45453555;subscriber=1;tmi-sent-ts=1616027196869;turbo=0;user-id=45453555;user-type= :leparklez!leparklez@leparklez.tmi.twitch.tv PRIVMSG #fulano :hello this breaks :)) :)`
Outputs:
username: `fulano :hello this breaks :))`
message: `)`

**Comment by parklez** [comment]
DEBUG    | i.twitch.tv PRIVMSG #bawkbasoup :nice this is the uncut version

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Andreas\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Andreas\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run   
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Andreas\Documents\GitHub\twitch-bot\parky_bot\twitch\bot.py", line 64, in pooling    
    m = Message(line)
  File "C:\Users\Andreas\Documents\GitHub\twitch-bot\parky_bot\models\message.py", line 31, in __init__
    self.parse()
  File "C:\Users\Andreas\Documents\GitHub\twitch-bot\parky_bot\models\message.py", line 55, in parse  
    self.message) = re.search(regex, self.string).groups()
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by parklez** [comment]
Nailed both with https://github.com/parklez/twitch-bot/commit/6b4cf573a0a3dfb96d60c9bf7591c31a0d6a1212
